### ISSUE TITLE
Economy System

### ISSUE THREAD

**Issue by privateY** [robinstechprojects/BankSystem#5]
Erstellend des Economy Systems, mit evt. Command Implementierung.

**Comment by privateY** [comment]
Jo, wird gemacht Sir.
Wichtig ist aber das man nicht von Anfang an ein Konto hat, sondern es erst manuell erstellen muss, z.B. in dem virtuellen Inventory von dir.

**Comment by robinstechprojects** [comment]
>Jo, wird gemacht Sir. ...

@privateY #7 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
